{
 "title": "MAAT · SERVIDOR · MONITOREO CLIENTES",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Fuente de Datos", "query": "prometheus" },
   {
    "name": "dns_job",
    "label": "Tipo DNS",
    "query": {
     "query": "label_values(up{job=~\"technitium-dns|unbound\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ESTADO DNS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$dns_job\"}"
    }
   ]
  },
  {
   "title": "DIRECCIÓN IP DEL SERVIDOR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  node_boot_time_seconds{instance=~\"[0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+(:[0-9]+)?\"}  or  up{job=\"$dns_job\",instance=~\"[0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+(:[0-9]+)?\"},\n  \"instance\", \"$1\", \"instance\", \"([0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+).*\"\n)"
    }
   ]
  },
  {
   "title": "USO DE CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": " Uso CPU"
    }
   ]
  },
  {
   "title": "USO DE CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "DISCO USO (%)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"}) / node_filesystem_size_bytes{mountpoint=\"/\"} * 100"
    }
   ]
  },
  {
   "title": "TIEMPO ENCENDIDO",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dias" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor((node_time_seconds - node_boot_time_seconds) / 86400)"
    }
   ]
  },
  {
   "title": "IPs usando el DNS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (client_ip) ({__name__=~\"technitium_dns_top_client_hits|unbound_client_queries_total\"}))"
    }
   ]
  },
  {
   "title": "USO DE RAM (GB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "RAM Usada"
    }
   ]
  },
  {
   "title": "MEMORIA (FÍSICA + FLOTANTE)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "En Uso"
    },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Flotante" }
   ]
  },
  {
   "title": "TRÁFICO DE RED (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\"}[1m]) / 1024 / 1024",
     "legendFormat": "Descarga (RX)"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\"}[1m]) / 1024 / 1024",
     "legendFormat": "Subida (TX)"
    }
   ]
  }
 ]
}